version: "3.7"
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017